### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ballyglunin1**
I want to make some silly changes to the repository codebase.

### CODE REVIEW

**Review by rowenaryan — COMMENTED** [review]
I don't like these changes. I think we keep the readme.ms as it currently is @Ballyglunin1

**Review by rowenaryan — COMMENTED** [review]
Can you @Ballyglunin1 make the required changes please.

**Review by rowenaryan — CHANGES_REQUESTED** [review]
Can you @Ballyglunin1 make the required changes please.

**Review by Ballyglunin1 — COMMENTED** [review]
I think you are correct. Thanks for reviewing.

**Comment by Ballyglunin1** [comment]
I think you are correct, thanks for reviewing

**Pull request closed without merging**
